name       : teckit
version    : 2.5.10
release    : 1
source     :
    - https://github.com/silnrsi/teckit/releases/download/v2.5.10/teckit-2.5.10.tar.gz : 269d12311bc37c57ebdec4aa539201c588030ddb4307c06e6924fb0e2d72168b
license    :
    - CPL-1.0
    - LGPL-2.1-or-later
component  : programming.tools
summary    : A Text Encoding Conversion toolkit
description: |
    TECkit is a low-level toolkit intended to be used by applications for conversions between text encodings. For example, it can be used when importing legacy text into a Unicode-based application.

    The primary component of TECkit is a library, the TECkit engine. The engine relies on mapping tables in a specific, documented binary format. The TECkit compiler creates these tables from plain-text, human-readable descriptions.
builddeps  :
    - pkgconfig(expat)
setup      : |
    %patch -p1 < $pkgfiles/teckit-soversion.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
